### ISSUE TITLE
i guess you forgot requirements.txt

### ISSUE THREAD

**Issue by ArghyadipBiswas** [Ankit404butfound/PyWhatKit#245]
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by Ankit404butfound** [comment]
Seems so, reverting the release.

**Comment by SigireddyBalasai** [comment]
This is resolved

**Comment by nitinsurya** [comment]
Oddly still seeing this error on v5.4.1.

System: Mac OS 12.5.1
Python: 3.9


![image](https://user-images.githubusercontent.com/1701314/217409320-bd76d5a5-596b-4a9c-b86f-549b872061a0.png)
