### ISSUE TITLE
playonyt problem

### ISSUE THREAD

**Issue by krojowska** [Ankit404butfound/PyWhatKit#67]
I try this: 
import pywhatkit
pywhatkit.playonyt('Beyonce')

Playonyt look like: 
def playonyt(topic):
    url = requests.get("http://mypywhatkit.herokuapp.com/playonyt?topic=" + topic).text
    print(url)
    web.open(url)

And I have error: 
![image](https://user-images.githubusercontent.com/49947345/119222956-2677b580-baf7-11eb-8fac-69bdd6b43f78.png)
![image](https://user-images.githubusercontent.com/49947345/119222967-3394a480-baf7-11eb-99d1-f20a673ff6c2.png)

**Comment by Ankit404butfound** [comment]
Please update the library to the latest version, type `pip install pywhatkit==4.7`
Now type `pywhatkit.playonyt(video, use_api=True)`
It will work.

**Comment by krojowska** [comment]
Ok i changed like this:
def playonyt(topic):
"""Will play video on following topic, takes about 10 to 15 seconds to load"""
url = 'https://www.youtube.com/results?q=' + topic
count = 0
cont = requests.get(url)
data = cont.content
data = str(data)
lst = data.split('"')
for i in lst:
    count+=1
    if i == 'WEB_PAGE_TYPE_WATCH':
        break
if lst[count-5] == "/results":
    raise Exception("No video found.")

#print("Videos found, opening most recent video")
# web.open("https://www.youtube.com"+lst[count-5])
web.open(url)
# return "https://www.youtube.com"+lst[count-5]
return url

**Comment by krojowska** [comment]
but it open like this:
![image](https://user-images.githubusercontent.com/49947345/119223175-40fe5e80-baf8-11eb-9cdb-9286bf70130b.png)
Before that, the first link would open right away and the song would play automatically. And now there are the search results.

**Comment by Ankit404butfound** [comment]
Yup, that's why I asked to update, this will be fixed.

**Comment by krojowska** [comment]
![image](https://user-images.githubusercontent.com/49947345/119223690-195cc580-bafb-11eb-9758-6ff9b4367453.png)
now it looke like... 
I had the same problems recently, I wrote to you from the account of the boyfriend nikodomi and it was displayed the same. I still have api heroku and it worked, but currently the api does not work anymore

**Comment by krojowska** [comment]
![image](https://user-images.githubusercontent.com/49947345/119223725-46a97380-bafb-11eb-8232-59687cdb7b8f.png)

**Comment by Ankit404butfound** [comment]
Yes, looks good.

**Comment by krojowska** [comment]
Any idea? I use this to create my master work...

**Comment by krojowska** [comment]
I can't see the movie, only error

**Comment by aaryanrr** [comment]
Hey @krojowska , is your problem resolved now?

**Comment by krojowska** [comment]
So, still the same :( 
I need this function working for my project.

Can this API still work? http://mypywhatkit.herokuapp.com/playonyt?topic=
Because it was very good and replaced the non-working playonyt function

**Comment by aaryanrr** [comment]
The API is down currently,, we are working to resolve it. If its urgent you can host the API for free on heroku for personal use.

**Comment by Ankit404butfound** [comment]
> So, still the same :(
> I need this function working for my project.
> 
> Can this API still work? http://mypywhatkit.herokuapp.com/playonyt?topic=
> Because it was very good and replaced the non-working playonyt function

Hey @krojowska, you can use pwk.playonyt("topic", use_api=True) or you can use this API http://pywhatkit.herokuapp.com/playonyt?topic=python. Bot should work.

**Comment by aaryanrr** [comment]
Oh the api in the code hasn't been updated.

**Comment by Ankit404butfound** [comment]
No, the code of GitHub isn't, in the actual pypi package, the url is pywhatkit.hero...... I actually forgot to update the code here. 😅😅
